#! /usr/bin/env bash

set -e
set -o pipefail
set -u

printf '>seq\nAAAAAAAAAAAAACCCCCCCCCCAAAAAAAAAAAAAAAAAAAAAAA\n' > isolate_1.fa
printf '>seq\nAAAAAAAAAAAAACCCCGCCCCCAAAAAAAAAAAAAAAAAAAA\n' > isolate_2.fa
printf '>seq\nAAAAAAAAAAAAACGTTTGGCGCCGGAAAAAAAAAAAAAAAAAAAAAAAAAA\n' > isolate_3.fa
printf '>seq\nAAAAAAAAAAAAATGTTTTTTGGCCGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' > isolate_4.fa
printf '>seq\nAAAAAAAAAAAAATGTTTTTTTTGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n' > isolate_5.fa

